# Activity 4: Linear Algebra and Linear Systems

In this activity we'll learn how python can help with managing linear systems of equations.

First let's look at manipulating matrices with python:

In [4]:
import numpy as np

#
# create a 3x3 matrix using numpy. The input is a list of lists
#

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

To create a matrix use the np.array constructor, but this time the argument is a list of lists. The outer list holds the three rows, and each inner list is a single row. You can experiment with arrays easily to see how they behave:

In [5]:
A+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
A*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Note that simple math with scalers operates on eacm of the elements of the array the same. You can also add arrays:

In [10]:
B=2*A # create a new matrix B that is 2 times A
B

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [11]:
A+B # add A and B

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [14]:
A*B # multiply A and B element by element

array([[  2,   8,  18],
       [ 32,  50,  72],
       [ 98, 128, 162]])

# The Scaler Product

There is a very useful operation between two vectors sometimes called the "dot" product, or "scaler" product. A dot product is computing by multiplying corresponding components of two individual vectors, and then calculating the sum of those products. Suppose $\vec{A}^{*}$ is a vector and $\vec{B}$ is a vector, like so

$$ \vec{A} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ \ \vec{B} = \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}$$

The *dot* *product* of $\vec{A}$ and $\vec{B}$ would be:

$$ \sum A_i B_i = 1\times 4 + 2 \times 5 + 3 \times 6 = 32 $$

In python one can accomplish this by using the "matrix multiplication" operator `@` like so:

In [17]:
A = np.array([1,2,3])
B = np.array([4,5,6])

A@B

32

There is a related concept called a *linear* *transformation* where a vector is linearly transformed into another vector. A linear transformation involves using this same matrix multiplication operator to compute the dot product of the three row vectors that make up the linear transoformation with the original vector:

Suppose:

$$ A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} $$

and 

$$ \vec{B} = \begin{bmatrix} 2 \\ 3 \\ 4 \end{bmatrix} $$

Then you can compute the linear transformation of $\vec{B}$ by $A$ as the vector whose components are the dot products of the rows of $A$ with $\vec{B}$.

Let $\vec{C}$ be the linear transformation:

$$ \vec{C} = A \vec{B} = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} \begin{bmatrix} 2 \\ 3 \\ 4 \end{bmatrix}$$

$$ \vec{C} = \begin{bmatrix} 1\times 2 + 2\times 3 + 3 \times 4 \\ 4 \times 2 + 5 \times 3 + 6\times 4 \\ 7\times 2 + 8\times 3 + 9\times 4 \end{bmatrix} = \begin{bmatrix} 20 \\ 47 \\ 74 \end{bmatrix}$$



In [20]:
#
# It looks hard, but in python it's actually super easy:
#

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([2,3,4])
C = A@B
C

array([20, 47, 74])

Another way to *think* of it is the linear combination, or superposition, of the columns of $A$ using the components of $\vec{B}$ as the coefficients:

$$\vec{C} = \begin{bmatrix} 1 \\ 4 \\ 7 \end{bmatrix} \times 2 +  \begin{bmatrix} 2 \\ 5 \\ 8 \end{bmatrix} \times 3 + \begin{bmatrix} 3 \\ 6 \\ 9 \end{bmatrix} \times 4 =  \begin{bmatrix} 20 \\ 47 \\ 74 \end{bmatrix}$$

As you can see you get the same result either way.

# Systems of Equations again

